export const SETTINGS = {
  NETWORK_CONNECTION_CHANGE: 'NETWORK_CONNECTION_CHANGE',
};

export const USER = {
  GET_USER: 'GET_USER',
  GET_USER_SUCCESS: 'GET_USER_SUCCESS',
  GET_USER_FAILURE: 'GET_USER_FAILURE',

  LOG_IN: 'LOG_IN',
  LOG_IN_SUCCESS: 'LOG_IN_SUCCESS',
  LOG_IN_FAILURE: 'LOG_IN_FAILURE',

  LOG_OUT: 'LOG_OUT',
  LOG_OUT_SUCCESS: 'LOG_OUT_SUCCESS',
  LOG_OUT_FAILURE: 'LOG_OUT_FAILURE',
};

export const RECIPES = {
  GET_RECIPES: 'GET_RECIPES',
  GET_RECIPES_SUCCESS: 'GET_RECIPES_SUCCESS',
  GET_RECIPES_FAILURE: 'GET_RECIPES_FAILURE',
};

export const MENU = {
  GET_MENU: 'GET_MENU',
  GET_MENU_SUCCESS: 'GET_MENU_SUCCESS',
  GET_MENU_FAILURE: 'GET_MENU_FAILURE',

  ADD_MENU_ITEM: 'ADD_MENU_ITEM',
  ADD_MENU_ITEM_SUCCESS: 'ADD_MENU_ITEM_SUCCESS',
  ADD_MENU_ITEM_FAILURE: 'ADD_MENU_ITEM_FAILURE',
};
